Added a basic build artefact archive, plus a build failure if there are any test failures.

diff --git a/.github/workflows/cluck2sesame.yml b/.github/workflows/cluck2sesame.yml
--- a/.github/workflows/cluck2sesame.yml
+++ b/.github/workflows/cluck2sesame.yml
@@ -13,16 +13,37 @@ jobs:
 
       - name: Install MPLABX
         run: |
-          sudo dpkg --add-architecture i386
-          sudo apt update -y
-          sudo apt install -y libc6:i386 libx11-6:i386 libxext6:i386 libstdc++6:i386 libexpat1:i386
-          src/firmware/build/install-mplabx.sh
+          sudo dpkg --add-architecture i386;
+          sudo apt update -y;
+          sudo apt install -y libc6:i386 libx11-6:i386 libxext6:i386 libstdc++6:i386 libexpat1:i386;
+          src/firmware/build/install-mplabx.sh;
 
       - name: Install Ceedling
         run: |
-          gem install rake
-          gem install ceedling
+          gem install rake;
+          gem install ceedling;
 
-      - name: Build
+      - name: Test
         run: |
-          src/firmware/ceedling test && src/firmware/ceedling verbosity[4] release
+          cd src/firmware;
+          ./ceedling test;
+          echo -e "\n\n[TEST FAILURE REPORTS]";
+          cat build/ceedling/generated/test/results/*.fail 2>/dev/null && exit 1;
+
+      - name: Build Release Artefact
+        run: |
+          cd src/firmware;
+          ./ceedling verbosity[4] release;
+
+      - name: Archive Build Artefacts
+        uses: actions/upload-artifact@v2
+        with:
+          name: Cluck2Sesame-Build
+          path: |
+            src/firmware/build/ceedling/generated/release/Cluck3Sesame.elf
+            src/firmware/build/ceedling/generated/release/Cluck3Sesame.hex
+            src/firmware/build/ceedling/generated/release/Cluck3Sesame.hxl
+            src/firmware/build/ceedling/generated/release/Cluck3Sesame.map
+            src/firmware/build/ceedling/generated/release/Cluck3Sesame.sym
+            src/firmware/build/ceedling/generated/release/Cluck3Sesame.s
+            src/schematics/Plots/Cluck2SesameSchematics.pdf
